# Change these first
owner: l1kw1d # Your GitHub organization or username, where this repository lives
repo: status.bunkers # The name of this repository
user-agent: l1kw1d

sites:
  - name: Bunkers
    url: https://bunkers.co
  - name: Zombie Graphique
    url: https://zombiegraphique.com
  - name: Maçonnerie David Deschambault Inc.
    url: https://maconneriemdd.com
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.bunkers.co
  # baseUrl: /your-repo-name
  logoUrl: https://privacy.bunkers.co/logo.quebec.inc.jpeg
  name: Bunkers Status
  introTitle: "**Bunkers** status, powered entirely by GitHub."
  introMessage: "🛡️ **Bunkers Status** – Surveillance en temps réel de notre infrastructure et services critiques pour une cybersécurité maximale. 📡  "
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Security
      href: https://privacy.bunkers.co/security-privacy

