owner: l1kw1d
repo: status.bunkers
user-agent: l1kw1d

sites:
  # 🔐 Internal Infrastructure (HIDDEN with GitHub Secrets)
  - name: Bunkers Main Website
    url: https://bunkers.co
    check: "http"
  - name: Bunkers Email Gateway
    url: em.zombie.solutions
    port: 587
    check: "tcp-ping"
    hidden: true

  status-website:
  cname: status.bunkers.co
  logoUrl: https://bunkers.co/logo.svg
  name: Bunkers Status
  introTitle: "**Bunkers Cyber Defense Status Page**"
  introMessage: |
    Welcome to the **Bunkers Cyber Defense** monitoring dashboard.  
    We provide **real-time updates** on the availability and security of our internal services, 
    as well as third-party providers we rely on.

  navbar:
    - title: Status
      href: /
    - title: Security Advisory
      href: https://privacy.bunkers.co/security-privacy

notifications:
  email:
    to: 
    subject: "[ALERT] {{name}} - {{status}}"
    body: |
      **Status Alert: {{name}}**
      - Status: {{status}}
      - Response Time: {{responseTime}} ms
      - Last Checked: {{lastCheck}}
      - More Info: [View Status Page](https://status.bunkers.co)

uptime-checks:
  interval: 3 # Check every 3 minutes
  retries: 3
  timeout: 8 # seconds

history:
  keep: 120 # Keep history for 120 days

alerts:
  notifyOn:
    - outage
    - degradedPerformance
    - majorUpdate

  autoCloseIssues: true

commitMessages:
  summaryJson: ":bar_chart: Update status summary [skip ci] [upptime]"
  statusChange: ":warning: {{name}} is {{status}} ({{responseCode}} in {{responseTime}} ms) [skip ci] [upptime]"
  graphsUpdate: ":chart_with_upwards_trend: Update graphs [skip ci] [upptime]"
